### PR TITLE
adding new functions proven useful w/ past several sheriffs

### PR DESCRIPTION
**Pull request by jessesarn**
Also includes:
- normalization of format for dynamic resolution of namespaces.
- improved support for RHMI 2.x
- added TODO tags for known limitations to existing code
- detects if script is called directly instead of being sourced

### CODE REVIEW

**Comment by jessesarn** [comment]
@JameelB / @ciaran-byrne can one of you verify and give a lgtm?

**Review by ciaran-byrne — APPROVED** [review]
/lgtm

**Pull request merged**
